<?= $this->include('layout_vertical/header');?>
<!--CSS Loaders [ OPTIONAL ]-->
<link href="<?=base_url('');?>/public/assets/plugins/css-loaders/css/css-loaders.css" rel="stylesheet">
<!--DataTables [ OPTIONAL ]-->
<link href="<?=base_url('');?>/public/assets/datatables/css/jquery.dataTables.min.css" rel="stylesheet">
<link href="https://cdn.datatables.net/buttons/1.6.5/css/buttons.dataTables.min.css" rel="stylesheet">
<!--CONTENT CONTAINER-->


<div id="content-container">
    <!--Page content-->
    <div id="page-content">
        <div class="panel panel-mint">
            <div class="panel-heading">
                <h5 class="panel-title">Date & Ward wise generated notice</h5>
            </div>
            <div class="panel-body">
            <form method="post" action="<?=base_url().'/propDtl/printNotice'?>"><div class="col-md-12">
				<div class="col-md-12">
					<div class="row">
						<label class="col-md-2 text-bold">From Date</label>
						<div class="col-md-3 has-success pad-btm">
							<input type="date" id="from_date" class="form-control" name="search_from_date" value="<?=date('Y-m-d');?>" />
						</div>
						<label class="col-md-2 text-bold">Upto Date</label>
						<div class="col-md-3 has-success pad-btm">
							<input type="date" id="upto_date" class="form-control" name="search_upto_date" value="<?=date('Y-m-d');?>" />
						</div>
					</div>
					<div class="row">
						<label class="col-md-2 text-bold">Ward No.</label>
						<div class="col-md-3 has-success pad-btm">
							<select id='ward_mstr_id' class="form-control" name="search_ward_mstr_id">
								<option value=''>ALL</option>
							<?php
							if (isset($wardList))
                            {
								foreach ($wardList as $list)
                                    {
                                    ?>
                                    <option value='<?=$list['id'];?>'><?=$list['ward_no'];?></option>
                                    <?php
								}
							}
							?>
							</select>
						</div>
                        <label class="col-md-2 text-bold">Notice Type</label>
						<div class="col-md-3 has-success pad-btm">
							<select id='notice_type' class="form-control" name="search_notice_type">
								<option value=''>ALL</option>
                                <option value='Assessment'>Assessment</option>
                                <option value='Demand'>Demand</option>
							</select>
						</div>
                    </div>
                    <div class="row">
                        <div class="col-md-12 text-center">
							<input type="button" id="btn_search" class="btn btn-primary" value="SEARCH" />                               
                            <span id="print_btn">
                           </span> 
						</div>
                    </div>
				</div>
                </form>
            </div>
        </div>

        <div class="panel panel-dark">
            <div class="panel-heading">
                <h5 class="panel-title">Result <span id="footerResult"></span></h5>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="table-responsive">
                            <table id="empTable" class="table table-striped table-bordered text-sm">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Notice No.</th>
                                        <th>Notice Date</th>
                                        <th>Notice Type</th>
                                        <th>Ward No.</th>
                                        <th>Holding No.</th>
                                        <th>Owner Name</th>
                                        <th>Mobile No.</th>
                                        <th><u>Demand</u> <br />From / Upto</th>
                                        <th>Amount</th>
                                        <th>Penalty Amount</th>
                                        <th>Generated Date</th>
                                        <th>Generated By</th>
                                        <th>Deactive Reason</th>
                                        <th>Deactived Date</th>
                                        <th>Deactived By</th>
                                    </tr>
                                </thead>
                                <tbody>

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--End page content-->
</div>
<!--END CONTENT CONTAINER-->
<?= $this->include('layout_vertical/footer');?>
<!--DataTables [ OPTIONAL ]-->
<script src="<?= base_url('');?>/public/assets/datatables/js/jquery.dataTables.min.js"></script>
<script src="<?= base_url('');?>/public/assets/datatables/js/dataTables.buttons.min.js"></script>
<script src="<?= base_url('');?>/public/assets/datatables/js/jszip.min.js"></script>
<script src="<?= base_url('');?>/public/assets/datatables/js/pdfmake.min.js"></script>
<script src="<?= base_url('');?>/public/assets/datatables/js/vfs_fonts.js"></script>
<script src="<?= base_url('');?>/public/assets/datatables/js/buttons.html5.min.js"></script>
<script src="<?= base_url('');?>/public/assets/datatables/js/dataTables.responsive.min.js"></script>
<script src="<?= base_url('');?>/public/assets/datatables/js/buttons.print.min.js"></script>

<script type="text/javascript">
$(document).ready(function(){
    jQuery.extend( jQuery.fn.dataTableExt.oSort, {
        "formatted-num-pre": function ( a ) {
            a = (a === "-" || a === "") ? 0 : a.replace( /[^\d\-\.]/g, "" );
            return parseFloat( a );
        }, 
        "formatted-num-asc": function ( a, b ) {
            return a - b;
        }, 
        "formatted-num-desc": function ( a, b ) {
            return b - a;
        }
    } );
	var recordsTotal = 0;
    var dataTable = $('#empTable').DataTable({
        'responsive': true,
        'processing': true,
        "deferLoading": 0, // default ajax call prevent
        'serverSide': true,
        dom: 'Bfrtip',
        lengthMenu: [
            [10, 25, 50, 5000],
            ['10 rows', '25 rows', '50 rows', '5000 rows']
        ],
        buttons: [
            'pageLength',
            {
                text: 'Excel Export',
                className: 'btn btn-primary',
                extend: "excel",
                title: "Ward Wise Generated Notice (<?=date ("Y-m-d H:i:s A")?>)",
                footer: { text: '' },
                exportOptions: { columns: [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15] }
            }
        ],
        'ajax': {
            "type": "POST",
            'url':'<?=base_url('prop_report/WardWiseGeneratedNoticeAjax');?>',
            dataSrc: function ( data ) {
                recordsTotal  = data.recordsTotal;
                return data.data;
            },
            "deferRender": true,
            "dataType": "json",
            'data': function(data){
                // Append to data
                data.search_from_date = $('#from_date').val();
                data.search_upto_date = $('#upto_date').val();
                data.search_ward_mstr_id = $('#ward_mstr_id').val();
                data.search_notice_type = $('#notice_type').val();
            },
            beforeSend: function () {
                $("#btn_search").val("LOADING ...");
				$("#loadingDiv").show();
            },
            complete: function () {
               $("#btn_search").val("SEARCH");
			   $("#loadingDiv").hide();
            },
        },
        'columns': [
            { 'data': 's_no' },
            { 'data': 'notice_no' },
            { 'data': 'notice_date' },
            { 'data': 'notice_type' },
            { 'data': 'ward_no' },
            { 'data': 'holding_no' },
            { 'data': 'owner_name' },
            { 'data': 'owner_mobile_no' },
            { 'data': 'from_upto_fy_qtr' },
            { 'data': 'demand_amount' },
            { 'data': 'penalty' },
            { 'data': 'generated_date' },
            { 'data': 'generated_by' },
            { 'data': 'remarks' },
            { 'data': 'deactivate_date' },
            { 'data': 'deactivated_by' },
        ],
        drawCallback: function( settings ) {
            try {
                $("#footerResult").html(" (Total Notice - "+recordsTotal+")");
                // var api = this.api();
                // $(api.column(2).footer() ).html(recordsTotal);
            } catch(err) {
                console.log(err.message);
            }
        }
    });
    $('#btn_search').click(function(){
        dataTable.draw();
    });
});

</script>
<script>
    $("select[name=search_notice_type]").on('change',function ()
    {
        if($(this).val()=="Demand")
        {
            $("#print_btn").html('<input type="submit" id="btn_print" class="btn btn-primary" value="PRINT" formtarget="_blank"/>');
        }else{
            $("#print_btn").html('');
        }
    })
</script>